name: ci
on: { push: { branches: [main] }, pull_request: { branches: [main] } }
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.12", cache: "pip" }
      - run: pip install -U pip setuptools wheel
      - run: pip install -r requirements.txt
      - name: Smoke test
        run: |
          python main.py --budget data/budget_plan.csv --actual data/actual_spend.csv --output artifacts/report.pptx
